# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Great_Vinyl_Exchange' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Great_Vinyl_Exchange

  target 'Great_Vinyl_Exchange-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Great_Vinyl_ExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
